# config.py
DEBOUNCE_MS = 120
BEEPER_PIN  = 15

MATRIX_SPI_ID = 0
MATRIX_SCK    = 18
MATRIX_MOSI   = 19
MATRIX_CS     = 17
MATRIX_NUM    = 4

SUNRISE_LEAD_MINUTES = 10
SUNRISE_START_PCT    = 2

LDR_PIN       = 26
LDR_THRESHOLD = 30000

FLASH_STOP_PIN     = 6
FLASH_TIMEOUT_MINS = 10

ALARM_HOUR   = 7
ALARM_MINUTE = 0

WIFI_SSID     = "your_network"
WIFI_PASSWORD = "your_password"
